services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo:/data/db
    env_file:
      - .env.public

  chromadb:
    image: chromadb/chroma
    volumes:
      - ./db/chroma:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - "8000:8000"
    env_file:
      - .env.public

  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: ai-container
    ports:
      - "8001:8000" # Map host port 8000 to container port 8000
    volumes:
      - ./ai/ai:/app/ai # Mount the app directory for hot-reloading
    env_file:
      - .env.public
      - .env.secret
    command: poetry run fastapi dev ./ai/main.py --host 0.0.0.0 --reload

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8002:8000" # Map host port 8000 to container port 8000
    volumes:
      - ./backend/backend:/app/backend # Mount the app directory for hot-reloading
    env_file:
      .env.public
    depends_on:
      - mongo
      - chromadb
      - ai
    command: poetry run fastapi dev ./backend/main.py --host 0.0.0.0 --reload
  
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui-container
    ports:
      - "8501:8501"
    volumes:
      - ./ui/ui:/app/ui # Mount the app directory for hot-reloading
    env_file:
      .env.public
    depends_on:
      - backend
    command: poetry run streamlit run ./ui/1_💬_Chat.py --server.address 0.0.0.0 --server.port 8501 --server.fileWatcherType auto